# Generated by Django 5.1.7 on 2025-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='designation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
