# Generated by Django 5.1.7 on 2025-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_designation_designation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_documents',
            field=models.FileField(blank=True, help_text='Upload employee documents', null=True, upload_to='employee_documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_resigning_reason',
            field=models.TextField(blank=True, help_text="Reason for employee's resignation", null=True),
        ),
    ]
