# Generated by Django 5.1.7 on 2025-07-14 10:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePunchin',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile Punch-in',
                'verbose_name_plural': 'Mobile Punch-ins',
                'db_table': 'mobile_punchin',
            },
        ),
        migrations.CreateModel(
            name='PunchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('punch_in_time', models.DateTimeField(blank=True, null=True)),
                ('punch_out_time', models.DateTimeField(blank=True, null=True)),
                ('punch_in_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_in_branches', to='hr.branches')),
                ('punch_out_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_out_branches', to='hr.branches')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_records', to='mobile_punchin.mobilepunchin')),
            ],
            options={
                'verbose_name': 'Punch Record',
                'verbose_name_plural': 'Punch Records',
                'db_table': 'punch_record',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
