# Generated by Django 5.1.7 on 2025-07-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('mobile_punchin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchrecord',
            name='punch_out_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punch_out_branches', to='hr.branches'),
        ),
    ]
